# Generated by Django 5.2.4 on 2025-07-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customerprofile_city_customerprofile_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
