# Generated by Django 5.2.4 on 2025-07-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_options_remove_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
