# Generated by Django 5.2.4 on 2025-07-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_created_at_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'weight')},
        ),
    ]
