# Generated by Django 5.2.4 on 2025-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='HomePageFeatured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Featured Products', max_length=100)),
                ('max_items', models.PositiveIntegerField(default=12, help_text='Limit number of products displayed')),
                ('products', models.ManyToManyField(help_text='Select products to display on the homepage', to='shop.product')),
            ],
        ),
    ]
